include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/gen/*
    - lib/l10n/gen/*
    - legacy/**
  plugins:
    - very_good_analysis
linter:
  rules:
    public_member_api_docs: false
