# This file is managed by very_good_cli
include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/gen/*
    - lib/l10n/gen/*
    - legacy/**
  plugins:
    - very_good_analysis
linter:
  rules:
    public_member_api_docs: false
    cascade_invocations: false
    lines_longer_than_80_chars: false
